Website/tweet_analysis/config/routes.rb
Rails.application.routes.draw do
  get 'portal/general', as: :general
  get 'portal/heatmap', as: :heatmap
  get 'portal/polygonmap', as: :polygonmap
  get 'portal/trend', as: :trend
  get 'portal/top_10', as: :top_10
  get 'portal/scenario', as: :scenario
  get 'portal/realtime', as: :realtime
  get 'portal/welcome', as: :welcome

  root 'portal#welcome'

end

Website/tweet_analysis/app/models/suburb_boundary.rb
class SuburbBoundary < CouchRest::Model::Base
    use_database 'suburb_boundaries'
    property :_id,      String
    # property :geometry, 

end

Website/tweet_analysis/app/models/tweet.rb
class Tweet < CouchRest::Model::Base
    use_database 'melbourne_tweets_ccc'
    property :_id,      String
    property :text,    String
end

Website/tweet_analysis/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Website/tweet_analysis/app/controllers/portal_controller.rb
class PortalController < ApplicationController

  def welcome
    @team_member={
      "Yangguang Shi" => "626689",
      "Shengming Yan" => "672435",
      "Runze Li" => "672450",
      "Zheyu Ji" => "738774",
      "Shixun huang" => "732318"
    }
  end

  def general
    @container=["device","sentiment"]
  end

  def polygonmap
    @data_feature={
      "general"=>"General",
      "population"=>"Population", 
      "edu"=>"Tertiery Education Rate", 
      "sentiment_positive"=>"Positive Sentiment Score",
      "sentiment_negative"=>"Negative Sentiment Score",
      "unemployment"=>"Unemployment rate",
      "income"=>"Average weekly income",
      "movie"=>"Mvoie related tweets per one hundred thousand people",
      "gym"=>"Gym related tweets per one hundred thousand people",
      "book"=>"Book related tweets per one hundred thousand people",
      "crime"=>"Crime related tweets per one hundred thousand people",
      "disease"=>"Disease related tweets per one hundred thousand people"
    }
  end

  def heatmap
    @data_feature={"movie"=>"Mvoie related tweets","gym"=>"Gym related tweets","book"=>"Book related tweets",
      "crime"=>"Crime related tweets","disease"=>"Disease related tweets"}
    end

    def trend
      @selection=["Daily","Weekly","Yearly"]
    end

    def top_10
      @container=["user","topic"]
    end

    def scenario
      @selection=["Sentiment","Movie","Gym","Book","Crime","Disease","Emoji"]
    end

    def realtime
    end

  end
  

Website/tweet_analysis/app/helpers/application_helper.rb
module ApplicationHelper
end

Website/tweet_analysis/app/helpers/portal_helper.rb
module PortalHelper
end

Website/tweet_analysis/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <li><%= link_to welcome_path , :class => "navbar-brand" do %> 
            <span>Melbourne</span>
          <% end %>
      </li>
      <!-- <a class="navbar-brand"><span>Melbourne</span></a> -->
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><%= link_to general_path , :onclick => 'poly_continue_flag=false;' do %> 
              <%= fa_icon "pie-chart", text: "General" %>
           <% end %>
        </li>
        <li><%= link_to trend_path , :onclick => 'poly_continue_flag=false;' do %> 
              <%= fa_icon "bar-chart", text: "Trend" %>
           <% end %>
        </li>
        <li><%= link_to polygonmap_path do 
              fa_icon "globe", text: "Polygonmap"
            end %>
        </li>
        <li><%= link_to heatmap_path, :onclick => 'poly_continue_flag=false;' do %> 
              <%=fa_icon "fire", text: "Heatmap"%>
           <%end %>
        </li>
        <li><%= link_to top_10_path, :onclick => 'poly_continue_flag=false;' do %> 
             <%= fa_icon "group", text: "Top 10"%>
           <%end %>
        </li>
        <li><%= link_to scenario_path, :onclick => 'poly_continue_flag=false;' do %> 
             <%= fa_icon "gears", text: "Scenario"%>
           <%end %>
        </li>
        <li><%= link_to realtime_path, :onclick => 'poly_continue_flag=false;' do %> 
             <%= fa_icon "hourglass-half", text: "Realtime"%>
           <%end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

Website/tweet_analysis/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TweetAnalysis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/modules/exporting.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkGOniAh0e3h5yJ1gcVP6ep1DqbIrUdzM&libraries=visualization"></script>
  <script src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/1.1.5/src/markerwithlabel_packed.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <%= yield %>
  
</body>
</html>

Website/tweet_analysis/app/views/portal/_sidebar.html.erb
<div class="sidebar-nav">
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav" id='side-menu'>
            <% selection.each do |x|%>
                <li onclick= '<%=function_name%>("<%= x %>")'> <%= x %><br>
            <% end %>
        </ul>
    </div>
</div>

Website/tweet_analysis/app/views/portal/general.html.erb
<% @container.each_with_index do |c,i|%>
    <div id="<%=c%>-container" class="col-md-6" style='min-width: 200px; height: 400px; margin: 0 auto; margin-bottom: 100px; <%= (i==0 || i==1) ? "margin-top: 170px" : ""%>'></div>
<% end%>
    <div id="emoji-distribution-container" class="col-md-12" style='min-width: 200px; height: 400px; margin: 0 auto; margin-bottom: 100px;'></div>
<script type="text/javascript">
initGeneralPieChart();
</script>

Website/tweet_analysis/app/views/portal/heatmap.html.erb
<script type="text/javascript">
// window.onload=function(){
//     if(fresh_flag){
//         fresh_flag=false;
//         window.location.reload();
//     }
// }</script>
<div id="data_display_panel" class="data_panel">
        <div id="sentiment_fan" style="height: 200px; margin: 0 auto"></div>
</div>
<div id="feature_panel" class="data_panel">
      <b>Feature selection</b><br>
      <% @data_feature.each do |k,v|%>
        <input type="radio" name="feature" onclick='setHeatMapFeatureData("<%= k %>")'> <%= v %><br>
      <% end %>
</div>
<div id="map"></div>
<script >
initHeatMap();
</script>

Website/tweet_analysis/app/views/portal/polygonmap.html.erb
<div id="data_display_panel" class="data_panel">
        <b>Data Collection : </b><span id='surburd-name'></span>
        <div id="panel-data">Hover over Melbourne area to get data</div>
</div>

<div id="feature_panel" class="data_panel">
      <b>Feature selection</b><br>
      <% @data_feature.each do |k,v|%>
        <input type="radio" name="feature" onclick='setFeatureData("<%= k %>")'> <%= v %><br>
      <% end %>
</div>

<div id="legend_panel" class="data_panel">
    <b>Feature legend</b>
    <div id="legend-data"></div>
</div>

<div id="map"></div>
<script >
  initPolyMap();
</script>

Website/tweet_analysis/app/views/portal/realtime.html.erb
<div id="legend_panel" class="data_panel">
    <button class="button" onclick="removeMarker()">clear tweets</button>
</div>

<div id="googleMap" style="width:100%;height:100%;"></div>

<script type="text/javascript">
initializeRealtimeMap();
</script>

Website/tweet_analysis/app/views/portal/scenario.html.erb
<div id="scenario_sidebar">
    <%= render :partial => '/portal/sidebar', :locals => {:selection=> @selection,:function_name=>"setComparisonChartData"}%>
</div> 
<div class="charts">
    <div id="comparison-chart-container" style="min-width: 310px; height: 600px; margin: 0 auto; margin-top: 100px"></div>
</div>
<div id="myProgress">
  <div id="myBar"></div>
</div>

<script type="text/javascript">
initScenarioChart();
</script>

Website/tweet_analysis/app/views/portal/top_10.html.erb
<% @container.each_with_index do |c,i|%>
    <div id="<%=c%>-container" style='min-width: 310px; height: 400px; margin: 0 auto; <%= i==0 ? "margin-top: 70px" : ""%>'></div>
<% end%>
<script type="text/javascript">
getTop20();
</script>

Website/tweet_analysis/app/views/portal/trend.html.erb
<%= render :partial => '/portal/sidebar', :locals => {:selection=> @selection,:function_name=>"setChartData"}%>
<div class="charts">
    <div id="mood-charts" style="min-width: 310px; height: 600px; margin: 0 auto; padding-top: 70px"></div>
</div>

<script type="text/javascript">
initCharts();
</script>

Website/tweet_analysis/app/views/portal/welcome.html.erb
<div id="welcome">
    <div id="team-table">
        <table class="table">
          <thead>
              <tr>
                <th>Student Name</th>
                <th>Student Number</th>
            </tr>
        </thead>
        <tbody>
          <% @team_member.each do |name,id| %>
          <tr>
            <td><%= name %></td>
            <td><%= id %></td>
        </tr>
        <% end %>
    </tbody>
</table>
</div>
</div>